CREATE TABLE [dbo].[Account]
(
	[AccountId] UNIQUEIDENTIFIER NOT NULL,
	[Username] NVARCHAR(30) NOT NULL,
	[Password] NVARCHAR(128) NOT NULL,
	[PasswordSalt] NVARCHAR(128) NOT NULL,

	CONSTRAINT [PK_Account] PRIMARY KEY([AccountId])
);